[package]
name = "rust"
version = "0.1.0"
authors = ["Connor Wood <connorwood71@gmail.com>"]
build = "build.rs"

[dependencies]
kaitai_struct = { git = "https://github.com/CWood1/kaitai_struct_rust_runtime" }
